site_name: Tharun Teja Mogili
site_url: https://tharun2104.github.io/Build-Website/

# Custom Homepage Elements
# home_cover_image: attachments/wizard-posting.png # This path starts at your root mkdocs directory.
# home_tagline: Shadow Wizards Only
# home_description: |
#   This site is an example showcase for my "mkdocs-coverpage" repository.
# # Gradient Color
# home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

theme:
  name: material
  # custom_dir: assets
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: "#6200ea"  # Deep Purple
      accent: "#03dac6"  # Teal
      warn: "#ff5722"    # Deep Orange
      background: "#121212"  # Dark Background
      text: "#e0e0e0"   # Light Text

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: "#6200ea"  # Light Purple
      accent: "#03dac6"   # Teal
      warn: "#cf6679"     # Soft Red
      background: "#ffffff"  # Light Background
      text: "#000000"     # Dark Text

# plugins:
#   - search
#   - roamlinks 

extra:
  # stylesheets:
  #   - style.css
    # - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Tharun2104
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tharuntejamogili/


extra_css:
  - styles.css
nav:
  - Home: index.md
  - Projects: Projects.md
  - Custom Page: custom-page.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/Tharun2104"  target="_blank" rel="noopener">Tharun Teja Mogili</a>

